name: my_wallet
description: "My Wallet"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  local_auth: ^2.3.0
  carousel_slider: ^5.0.0
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  equatable: ^2.0.7
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  mocktail: ^1.0.4
  no_screenshot: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
